### ISSUE TITLE
SPPlist::load() -> ERROR : keyNotFound(CodingKeys(stringValue: "Theme", intValue: nil), Swift.DecodingError.Context(codingPath: [], debugDescription: "No value associated with key CodingKeys(stringValue: \"Theme\", intValue: nil) (\"Theme\").", underlyingError: nil))

### ISSUE THREAD

**Issue by BalajiAnandan15** [stipop-development/stipop-ios-sdk-demo#1]
SPPlist::load() -> ERROR : keyNotFound(CodingKeys(stringValue: "Theme", intValue: nil), Swift.DecodingError.Context(codingPath: [], debugDescription: "No value associated with key CodingKeys(stringValue: \"Theme\", intValue: nil) (\"Theme\").", underlyingError: nil))

**Comment by lbr0452000** [comment]
Hi, Thanks for trying our demo app!

This problem is occured when Stipop SDK version and Stipop.plist version are different.

Please update demo app into latest commit and re-download Stipop.plist at [here](https://dashboard.stipop.io/)
